module BranchALU(
    input [31:0]    a,  //! rs1
    input [31:0]    b,  //! rs2 / imm
    input [4:0]     ALUCtrl,    //! ALU operation selected from ALU control
    output reg      BranchALUOutput
);

//! Select the operation needed based on ALUCtrl, signal generated by ALUControl by decoding instruction.
always@(*) begin : BranchAluOperation
    case(ALUCtrl)
        26: BranchALUOutput = a == b;                    //BEQ
        27: BranchALUOutput = a != b;                    //BNE
        28: BranchALUOutput = $signed(a) < $signed(b);   //BLT
        29: BranchALUOutput = $signed(a) >= $signed(b);  //BGE
        30: BranchALUOutput = a < b;                     //BLTU
        31: BranchALUOutput = a >= b;                    //BGEU
        default: BranchALUOutput = 0;
    endcase
end

endmodule
